---
apiVersion: v1
kind: Service
metadata: 
  name: spc-svc
  labels:
    topic: service
spec:
  selector:
    app: spc
  type: NodePort
  ports:
    - name: spc-port
      nodePort: 31000
      port: 8080
      targetPort: 8080
