apiVersion: apps/v1
kind: Deployment
metadata: 
  name: practice-deploy
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec:
      containers:
        - name: web
          image: apache
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
        - name: alpine
          image: alpine
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              cpu: 500M
              memory: 500Mi
          args:
            - sleep
            - 1d

