apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http-port
      port: 80
      targetPort: 80
    - name: alpine-port
      port: 8080
      targetPort: 8080
      NodePort: 30001


  
