apiVersion: v1
kind: ReplicationController
metadata: 
  name: trail1
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
             - containerPort: 80
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi

      
