apiVersion: v1
kind: ReplicationController
metadata: 
  name: trail1
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        env: production
        app: alpine
    spec:
      containers:
        - name: alpine
          image: alpine
          args:
            - sleep
            - 1d
          resources:
            limits:
              cpu: 2000m
              memory: 500Mi

      
