apiVersion: apps/v1
kind: Deployment
metadata:
  name: exe-2
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache-pod
          image: httpd
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
        - name: alpine-pod
          image: alpine
          ports:
            - containerPort: 80
          args:
            - sleep
            - 1d
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1



      
