---
apiVersion: apps/v1
kind: Deployment
metada:
  name: trail-deploy
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      labels:
        app: web
        version: "v1.0"
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80
      resources:
        limits:
          memory: 256Mi
          cpu: 500m

      
    
