apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      name: web-port
      

