---
apiVersion: v1
kind: Pod
metadata: 
  name: db
  labels:
    app: db-trail
spec:
  containers:
    - name: mysql-db
      image: mysql:8.0
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: devops@123
        - name: MYSQL_DATABASE
          value: db-trail
        - name: MYSQL_USER
          value: devops
        - name: MYSQL_PASSWORD
          value: devops
      resources:
        limits:
          cpu: "1000m"
          memory: "500Mi"
        
          