apiVersion: v1
kind: Pod
metadata: 
  name: postgress-db
  labels:
    app: postgress-db
spec:
  containers:
    - name: postgress-db
      image: postgres:16
      ports:
        - containerPort: 5432
          protocol: TCP
      env: 
       - name: POSTGRES_DB
         value: db-trail
       - name: POSTGRES_USER
         value: devops
       - name: POSTGRES_PASSWORD
         value: devops
      resources:
        limits:
          cpu: "1m"
          memory: "2.5Gi"
        requests:
          cpu: "0.5m"
          memory: "1Gi"
          
