apiVersion: v1
kind: Pod
metadata:
  name: init-cont
  labels:
    app: alpine
    topic: init-containers
spec:
  initContainers:
    - name: alpine-init
      image: alpine
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1000m"
          memory: "0.5Gi"
  