---
apiVersion: v1
kind: Service
metadata:
  name: practice-svc
spec:
  selector:
    app: tomcat 
  type: NodePort
  ports:
    - name: svc-port
      port: 80
      targetPort: 80
      nodePort: 31000
      