---
apiVersion: v1 
kind: Pod
metadata:
  name: antiaffinity
  labels:
    name: antiaffinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels: 
              name: bpod
          topologyKey: kubernetes.io/hostname
  containers:
  - name: antiaffinity
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
