apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deployment
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  replicas: 10
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: jenkins
        version: "v1.0"
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:jdk11
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
          ports: 
            - containerPort: 8080
  