apiVersion: batch/v1
kind: CronJob
metadata:
  name: dummy-cj
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      name: dummy-job
    spec:
      template: 
        metadata:
          labels: 
            app: job 
            name: dummy-pod
        spec:
          restartPolicy: Never
          containers:
            - name: dummy-ctr
              image: alpine
              args: 
                - sleep
                - 1d

              