---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deploy
spec:
  minReadySeconds: 20
  replicas: 2
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
        - name: spc-trail
          image: khotvp/spc:1.1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 1000m
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1



      

