---
- name: install tree
  hosts: all
  become: yes
  tasks: 
    - name: install tree on ubuntu 
      ansible.builtin.apt: 
          name: tree
          state: present 
          update_cache: yes
