apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: spc-rs
  labels:
    app: spc
    topic: ReplicaSet
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spc
      env: dev
  template:
    metadata:
      labels:
        app: spc
        env: dev
    spec:
      containers:
        - name: spc
          image: khotvp/spc:1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "500Mi"
        
        
      