apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  minReadySeconds: 30
  replicas: 10
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins-pod
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 2000m
              cpu: 2Gi