apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
      nodePort: 30001