apiVersion: v1
kind: Pod
metadata:
  name: affinity
  labels:
    name: affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              name: bpod
          topologyKey: kubernetes.io/hostname
  containers:
    - name: affinity
      image: ngnix
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
    



