---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs 
  labels:
    app: spc
    env: dev
    version: v3.4.0
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spc
      env: dev
      version: v3.4.0
  template:
    metadata:
      name: spc
      labels:
        app: spc
        env: dev
        version: v3.4.0
    spec:
      containers:
        - name: spc
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
              
