---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
  labels:
    app: spc
    env: dev
    version: v3.4.0
spec:
  type: NodePort
  selector:
    app: spc
  ports:
    - name: spc-port
      nodePort: 31000
      port: 8080
      targetPort: 8080